services:
  sentinel-1:
    image: falkordb/falkordb:edge
    container_name: sentinel-1
    hostname: sentinel-1
    restart: always
    networks:
      - falkordb-network
    ports:
      - 26379:26379
    entrypoint: /bin/bash
    healthcheck:
      test: |
        redis-cli -p 26379 ping || {echo "Sentinel is not ready"; exit 1}
      interval: 30s
      timeout: 10s
      retries: 5
    command:
      - -c 
      - |
        touch /data/sentinel.conf
        echo "sentinel monitor master falkordb-server-1 6380 2" >> /data/sentinel.conf
        echo "sentinel announce-hostnames yes"                  >> /data/sentinel.conf
        echo "sentinel announce-ip sentinel-1"                  >> /data/sentinel.conf
        echo "sentinel resolve-hostnames yes"                   >> /data/sentinel.conf
        echo "sentinel announce-port 26379"                     >> /data/sentinel.conf
        echo "port 26379"                                       >> /data/sentinel.conf
        redis-server /data/sentinel.conf --sentinel

  sentinel-2:
    image: falkordb/falkordb:edge
    container_name: sentinel-2
    hostname: sentinel-2
    restart: always
    networks:
      - falkordb-network
    ports:
      - 26380:26380
    entrypoint: /bin/bash
    healthcheck:
      test: |
        redis-cli -p 26379 ping || {echo "Sentinel is not ready"; exit 1}
      interval: 30s
      timeout: 10s
      retries: 5
    command:
      - -c
      - |
        touch /data/sentinel.conf
        echo "sentinel monitor master falkordb-server-1 6380 2" >> /data/sentinel.conf
        echo "sentinel announce-hostnames yes"                  >> /data/sentinel.conf
        echo "sentinel announce-ip sentinel-2"                  >> /data/sentinel.conf
        echo "sentinel resolve-hostnames yes"                   >> /data/sentinel.conf
        echo "sentinel announce-port 26380"                     >> /data/sentinel.conf
        echo "port 26380"                                       >> /data/sentinel.conf
        redis-server /data/sentinel.conf --sentinel
  
  sentinel-3:
    image: falkordb/falkordb:edge
    container_name: sentinel-3
    hostname: sentinel-3
    restart: always
    networks:
      - falkordb-network
    ports:
      - 26381:26381
    entrypoint: /bin/bash
    healthcheck:
      test: |
        redis-cli -p 26379 ping || {echo "Sentinel is not ready"; exit 1}
      interval: 30s
      timeout: 10s
      retries: 5
    command:
      - -c
      - |
        touch /data/sentinel.conf
        echo "sentinel monitor master falkordb-server-1 6380 2" >> /data/sentinel.conf
        echo "sentinel announce-hostnames yes"                  >> /data/sentinel.conf
        echo "sentinel announce-ip sentinel-3"                  >> /data/sentinel.conf
        echo "sentinel resolve-hostnames yes"                   >> /data/sentinel.conf
        echo "sentinel announce-port 26381"                     >> /data/sentinel.conf
        echo "port 26381"                                       >> /data/sentinel.conf
        redis-server /data/sentinel.conf --sentinel

  falkordb-server-1:
    image: falkordb/falkordb:edge
    hostname: falkordb-server-1
    container_name: falkordb-server-1
    ports:
      - 6380:6380
    networks:
      - falkordb-network
    entrypoint: /bin/bash
    healthcheck:
      test: |
        redis-cli -p 6380 ping || {echo "Redis is not ready"; exit 1}
      interval: 30s
      timeout: 10s
      retries: 5
    command:
      - -c
      - |
        touch /data/node.conf
        echo "port 6380" >> /data/node.conf 
        echo "replica-announce-ip falkordb-server-1"        >> /data/node.conf
        echo "replica-announce-port 6380"                   >> /data/node.conf
        echo "loadmodule /var/lib/falkordb/bin/falkordb.so" >> /data/node.conf
        redis-server /data/node.conf
  
  falkordb-server-2:
    image: falkordb/falkordb:edge
    hostname: falkordb-server-2
    container_name: falkordb-server-2
    ports:
      - 6381:6381
    networks:
      - falkordb-network
    entrypoint: /bin/bash
    healthcheck:
      test: |
        redis-cli -p 6381 ping || {echo "Redis is not ready"; exit 1}
      interval: 30s
      timeout: 10s
      retries: 5
    command:
      - -c
      - |
        touch /data/node.conf
        echo "port 6381" >> /data/node.conf 
        echo "replica-announce-ip falkordb-server-2"        >> /data/node.conf
        echo "replica-announce-port 6381"                   >> /data/node.conf
        echo "loadmodule /var/lib/falkordb/bin/falkordb.so" >> /data/node.conf
        echo "replicaof falkordb-server-1 6380"             >> /data/node.conf
        redis-server /data/node.conf

networks:
  falkordb-network:
